"""upgrade db

Revision ID: abe281a69404
Revises: b9a9e1556498
Create Date: 2026-03-07 20:42:06.536910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe281a69404'
down_revision: Union[str, Sequence[str], None] = 'b9a9e1556498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('discounts_product_id_fkey'), 'discounts', type_='foreignkey')
    op.create_foreign_key(None, 'discounts', 'products', ['product_id'], ['id'])
    op.drop_constraint(op.f('product_content_product_id_fkey'), 'product_content', type_='foreignkey')
    op.create_foreign_key(None, 'product_content', 'products', ['product_id'], ['id'])
    op.add_column('product_variants', sa.Column('new', sa.Boolean(), nullable=False))
    op.add_column('product_variants', sa.Column('brand', sa.String(), nullable=False))
    op.add_column('product_variants', sa.Column('product_type', sa.String(), nullable=False))
    op.drop_constraint(op.f('product_variants_product_id_fkey'), 'product_variants', type_='foreignkey')
    op.create_foreign_key(None, 'product_variants', 'products', ['product_id'], ['id'])
    op.drop_column('products', 'product_id')
    op.drop_constraint(op.f('rating_product_id_fkey'), 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'products', ['product_id'], ['id'])
    op.drop_constraint(op.f('review_product_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_product_id_fkey'), 'review', 'products', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key(op.f('rating_product_id_fkey'), 'rating', 'products', ['product_id'], ['product_id'])
    op.add_column('products', sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.create_foreign_key(op.f('product_variants_product_id_fkey'), 'product_variants', 'products', ['product_id'], ['product_id'])
    op.drop_column('product_variants', 'product_type')
    op.drop_column('product_variants', 'brand')
    op.drop_column('product_variants', 'new')
    op.drop_constraint(None, 'product_content', type_='foreignkey')
    op.create_foreign_key(op.f('product_content_product_id_fkey'), 'product_content', 'products', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.create_foreign_key(op.f('discounts_product_id_fkey'), 'discounts', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
